spring.application.name=anunciadores
server.port=5000

# spring security Configuration
#spring.security.user.name=- ilich
#spring.security.user.password 1234


# kafka Configuration
spring.kafka.bootstrapServers= localHost:9092 



#Data source
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Url donde esta el servicio de tu mysql y el nombre de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/anunciadb?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false

#Usuario y contrasena
spring.datasource.username=root
spring.datasource.password=Ifv.891123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true

spring.servlet.multipart.max-file-size = 20MB
spring.servlet.multipart.max-request-size = 20MB

token = 08987d61f822b061818f1471af309368
propiedad.telegram.token= 8308684604:AAFa7OnIfnLHJ_Okinymk4TE0ytzHm3a77Q

# JWT
security.jwt.secret=ghk45jgherogho834go3h4g
security.jwt.issuer=Main
#La sesion dura una semana
security.jwt.ttlMillis=604800000

# Activar logs detallados para tu cliente Feign
logging.level.com.anunciadores.client.TelegramClient=DEBUG

# Activar logs generales para Feign
logging.level.feign=DEBUG


cloudflare.r2.access-key=10dba0e742a05a5976e238644c3e11e9
cloudflare.r2.secret-key=7fea5cc9b5d0959e1c10ed32a87d7d24ba58765fb375384c2d9f4d0a8ab02b88
#https://pub-becb4bed35ee4164bb962059a8a24532.r2.dev
cloudflare.r2.endpoint=https://f706b8997ce106293efe0202af4d2046.r2.cloudflarestorage.com
cloudflare.r2.bucket=tcd-diario
cloudflare.r2.public-url=https://pub-becb4bed35ee4164bb962059a8a24532.r2.dev

